### PR TITLE
Added support for OSX

### PR DESCRIPTION
**Pull request by aurora**
I've made some modifications to get this thing to compile on OSX. I've tested on OSX 10.9 and everything (file transfer ;) seems to work, even though i get the error:

```
ERROR: On forking, highest fd should be 2 but it's 4
```

from utils.c, when starting rzh

### CODE REVIEW

**Comment by bronson** [comment]
Whoa, does rzh actually work for you??  I haven't looked at this code in almost a decade. You probably know more about it than I do.

Got the flu right now but looking forward to checking out this patch in the next few days.

**Comment by aurora** [comment]
Yes, rzh is a very useful tool. Your code is already very portable, the only tricky part was that there is no "clock_gettime" function available on OSX, the solution for this in fact is not from me, but collected from various other sources like stackoverflow and gist.github ... with the patches applied the code compiles without any further issue and works like a charm!

**Comment by bronson** [comment]
So...  I completely forgot about this.  I reworked a few things to try to reduce the number of #ifdef __APPLE__ guard clauses.  Hope it still works for you.

Thanks for the PR!  Sorry for the going on 3 year delay.

**Comment by aurora** [comment]
is it really already 3 years!? Time is passing by fast ... Thanks for merging! :-)

**Pull request merged**
